### ISSUE TITLE
DROP MIRROR throws error when no error occurs

### ISSUE THREAD

**Issue by marshallm94** [PeerDB-io/peerdb#3120]
# What version of PeerDB are you running?

```yaml
  peerdb:
    container_name: peerdb-server
    stop_signal: SIGINT
    image: ghcr.io/peerdb-io/peerdb-server:stable-v0.26.7
    restart: unless-stopped
    environment:
      <<: *catalog-config
      PEERDB_PASSWORD:
      PEERDB_FLOW_SERVER_ADDRESS: grpc://flow_api:8112
      RUST_LOG: info
      RUST_BACKTRACE: 1
    networks:
      - peerdb_network
    ports:
      - 9900:9900
    depends_on:
      catalog:
        condition: service_healthy
```

# What is the expected behavior?

When I run `DROP MIRROR {mirror_name};`, the mirror is dropped *without any errors being thrown*.

# What is the current behavior?

Running `DROP MIRROR {mirror_name};` successfully drops the mirror (as in the mirror no longer shows up in the PeerDB front-end), however an error is thrown saying `ERROR:  unable to delete job metadata: unable to delete flow job metadata`:

```sql
dev0=> DROP MIRROR my_mirror;
ERROR:  unable to delete job metadata: unable to delete flow job metadata

Stack backtrace:
   0: anyhow::error::<impl anyhow::Error>::msg
   1: peerdb_server::NexusBackend::handle_query::{{closure}}
   2: <peerdb_server::NexusBackend as pgwire::api::query::SimpleQueryHandler>::do_query::{{closure}}
   3: pgwire::api::query::SimpleQueryHandler::on_query::{{closure}}
   4: pgwire::tokio::server::process_socket::{{closure}}
   5: peerdb_server::main::{{closure}}::{{closure}}
   6: tokio::runtime::task::core::Core<T,S>::poll
   7: tokio::runtime::task::harness::Harness<T,S>::poll
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   9: tokio::runtime::scheduler::multi_thread::worker::Context::run
  10: tokio::runtime::context::runtime::enter_runtime
  11: tokio::runtime::scheduler::multi_thread::worker::run
  12: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::core::Core<T,S>::poll
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
  16: std::sys::backtrace::__rust_begin_short_backtrace
  17: core::ops::function::FnOnce::call_once{{vtable.shim}}
  18: std::sys::pal::unix::thread::Thread::new::thread_start

```
